runtime: java
env: flex
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 5
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10
runtime_config:
  jdk: openjdk8
handlers:
- url: /.*
  script: this field is required, but ignored